version: '2.1'

services:
  logger:
    image: logger
    build: .
    depends_on:
     - mongo
    volumes:
      - ../:/app
    ports:
      - 8888:5000
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./logger.py
  mongo:
    image: "mongo"
    ports:
      - 27017:27017
